---
name: build workflow
on:
  schedule:
    - cron: "5 8/12 * * *"
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        family: [tiny, normal, huge]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
      - name: ruby setup
        uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651 # v1.245.0
      - name: asdf plugin test
        uses: asdf-vm/actions/plugin-test@1902764435ca0dd2f3388eea723a4f92a4eb8302 # v4.0.0
        env:
          ASDF_VIM_TYPE: ${{ matrix.family }}
          ASDF_VIM_CONFIG: "--with-tlib=ncurses --with-compiledby=asdf-github-action"
        with:
          command: vim --version
