name: depup
on:
  schedule:
    - cron: "35 9 2,13,25 * *" # Runs at 9:35 UTC 2,13,25 per month
  repository_dispatch:
    types: [depup]
  workflow_dispatch:

jobs:
  ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true

      - name: Check depup
        uses: haya14busa/action-depup@94a1aaf4e4923064019214b48a43276218af7ad5 # v1.6.4
        id: depup
        with:
          file: .github/workflows/build.yml
          version_name: RUBY_VERSION
          repo: ruby/ruby

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore(deps): update ruby to ${{ steps.depup.outputs.latest }}"
          commit-message: "chore(deps): update ruby to ${{ steps.depup.outputs.latest }}"
          body: |
            Update ruby to [v${{ steps.depup.outputs.latest }}](https://github.com/ruby/ruby/releases/tag/${{ steps.depup.outputs.latest }})
            Compare [${{ steps.depup.outputs.current }}...v${{ steps.depup.outputs.latest }}](https://github.com/ruby/ruby/compare/v${{ steps.depup.outputs.current }}...v${{ steps.depup.outputs.latest }})

            This PR is auto generated by [depup workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3Adepup).
          branch: depup/ruby
          base: master
