---
name: Schedule workflow
on:
  schedule:
    - cron: "5 8/12 * * *"
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: ruby setup (mac)
        if: matrix.os == 'macOS-latest'
        uses: ruby/setup-ruby@dffc446db9ba5a0c4446edb5bca1c5c473a806c5 # v1.235.0
        with:
          ruby-version: 2.6
      - name: asdf plugin test
        uses: asdf-vm/actions/plugin-test@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3.0.2
        with:
          command: vim --version
